[build]
  command = "npm run build"
  publish = ".next/standalone" # Directorio correcto para 'output: standalone'
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NEXT_PUBLIC_NETLIFY = "true"