[build]
  command = "npm run build && npx @netlify/plugin-nextjs"
  publish = ".next/server/pages"  # Directorio que Next.js realmente usa
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NEXT_PUBLIC_NETLIFY = "true"