[build]
  command = "npm run build"
  publish = ".next/serverless"  # Directorio clave para Next.js en Netlify
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NEXT_PUBLIC_NETLIFY = "true"