[build]
  command = "npm run build && cp -R .next/static .next/standalone/.next/static"
  publish = ".next/standalone/.next/server/pages"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    skip_plugin = false

[context.production.environment]
  NEXT_PUBLIC_NETLIFY = "true"