[build]
  command = "npm run build && cp -R .next/static .next/standalone/.next/static && cp -R .next/server .next/standalone/.next/server"
  publish = ".next/standalone"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NEXT_PUBLIC_NETLIFY = "true"